const main = async () => {
  while (true) {
    try {
      console.log('init');
    } catch (err) {
      throw new Error(err)
    }
  }
}
